### ISSUE TITLE
Prefiring

### ISSUE THREAD

**Issue by mcremone** [mcremone/decaf#19]

**Comment by mcremone** [comment]
https://twiki.cern.ch/twiki/bin/viewauth/CMS/L1ECALPrefiringWeightRecipe

https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/python/postprocessing/modules/common/PrefireCorr.py

**Comment by Quantumapple** [comment]
Prefiring maps in root file
https://lathomas.web.cern.ch/lathomas/TSGStuff/L1Prefiring/PrefiringMaps_2016and2017/

**Comment by mcremone** [comment]
This has been solved: https://github.com/mcremone/decaf/blob/master/analysis/processors/darkhiggs.py#L1105

Weights are included in NanoAOD for 2016 and 2017 datasets.

Keeping open just to keep track of the issue description and the solution.
