### ISSUE TITLE
Missing compatibility with el8 and el9 nodes

### ISSUE THREAD

**Issue by alejands** [mcremone/decaf#78]
The current [`setup_lcg.sh`](https://github.com/mcremone/decaf/blob/8e989f5b9b4d1f6e0f9f4077cabe28452c2ba6ca/setup_lcg.sh) and [`env_lcg.sh`](https://github.com/mcremone/decaf/blob/8e989f5b9b4d1f6e0f9f4077cabe28452c2ba6ca/env_lcg.sh) files are configured to use nodes running SL6 or CC7 operating systems.

https://github.com/mcremone/decaf/blob/8e989f5b9b4d1f6e0f9f4077cabe28452c2ba6ca/env_lcg.sh#L1-L7

This works for the time being, as the default node on the LPC cluster still runs on SL7 (which appears to be compatible), however this may be soon become deprecated given that [lxplus has switched it's default alias to EL9](https://cern.service-now.com/service-portal?id=outage&n=OTG0076556) as of December 7, 2023.

Currently the LPC offers SL7 and EL8 nodes, and likewise for their GPU nodes. Both scripts above are able to run on SL7 nodes with no issues, but on EL8 nodes the `python` executable no longer exists, only `python3` which these scripts can't find.

```
[alejands@cmslpc205 decaf]$ . env_lcg.sh
-bash: python: command not found
-bash: python: command not found
Error in find.package("readr") : there is no package called ‘readr’
Calls: cat -> find.package
Execution halted
dirname: missing operand
Try 'dirname --help' for more information.
```

You can use `python` after sourcing a CMSSW environment with `cmsenv`, but you run into a different error of the LCG files no longer being available on these nodes.

```
[alejands@cmslpc204 decaf]$ echo $CMSSW_BASE
/uscms_data/d3/alejands/MonoZprime/CMSSW_10_6_30_patch1

[alejands@cmslpc204 decaf]$ . env_lcg.sh
/cvmfs/sft.cern.ch/lcg/releases/R/3.5.3-883db/x86_64-centos7-gcc8-opt/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
``` 

I don't believe this is an immediate cause for concern and we should focus on the UL issues first, but I'm posting it as an issue so it doesn't slip our minds. This feels like it should be straightforward to update (fingers crossed 🤞).

**Comment by mcremone** [comment]
You cannot use `python` after sourcing CMSSW, that would create a mess, even if you can make it work. I think all we need to do is to find the `setup.sh` script that works.

**Comment by alejands** [comment]
> You cannot use `python` after sourcing CMSSW, that would create a mess, even if you can make it work.

Noted. Good to know.

**Comment by mcremone** [comment]
While I couldn't find scripts for el8 easily, I was able to find a bunch for el9 by doing:

ls /cvmfs/sft.cern.ch/lcg/views/ * / * el9 *

Let's keep this in mind when the time comes. Also, we rarely run at lxplus. We use mostly KISTI and LPC.

**Comment by alejands** [comment]
@mcremone In which case, should we close this issue as "not planned" and come back to this later, or leave it open for the time being?

**Comment by alejands** [comment]
No longer relevant after migrating to using the Python 3.8 inside `CMSSW_11_3_4`. 

See:
- #83 
- #84
