### ISSUE TITLE
UL: Signal Cross Sections

### ISSUE THREAD

**Issue by mcremone** [mcremone/decaf#91]
Signal cross sections need to be added here:

https://github.com/mcremone/decaf/blob/UL/analysis/data/process.py#L104-L133

Use the real cross sections instead of 1.

**Comment by ParticleChef** [comment]
Updated the signal cross sections 
https://github.com/ParticleChef/decaf/blob/UL/analysis/data/process.py

**Comment by mcremone** [comment]
@ParticleChef can you make a pull request?
